Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CLDV6221_PoE_Part3.Models;

namespace CLDV6221_PoE_Part3.Controllers
{
    public class CarController : Controller
    {
        private readonly RideYouRentContext _context;

        public CarController(RideYouRentContext context)
        {
            ViewBag.bLoggedIn = Loggedin.CheckLoggedIn();
            if (Loggedin.bLoggedIn)
            {
                _context = context;
            }
            else
            {
                _context = context;
                _context.Car = null; 
                //set to null to avoid user bypassing the login and going to the page directly

            }
        }

        

        // GET: Car
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Car == null)
            {
                return Problem("Entity set 'CLDV6221_PoE_Part3Context.Car'  is null.");
            }

            var cars = from c in _context.Car.Include(c => c.CarBodyType).Include(c => c.CarMake)
                       select c;

            return View(await cars.ToListAsync());
        }

        // GET: Car/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .Include(c => c.CarBodyType)
                .Include(c => c.CarMake)
                .FirstOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Car/Create
        public IActionResult Create()
        {
            ViewData["CarBodyTypeId"] = new SelectList(_context.CarBodyTypes, "CarBodyTypeId", "Description");
            ViewData["CarMakeId"] = new SelectList(_context.CarMakes, "CarMakeId", "Description");
            return View();
        }

        // POST: Car/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarId,CarNo,CarMakeId,CarBodyTypeId,Model,KilometersTravelled,ServiceKilometers,Available")] Car car)
        {
            ViewData["CarBodyTypeId"] = new SelectList(_context.CarBodyTypes, "CarBodyTypeId", "Description", car.CarBodyTypeId);
            ViewData["CarMakeId"] = new SelectList(_context.CarMakes, "CarMakeId", "Description", car.CarMakeId);

            ModelState.Remove("CarMake");
            ModelState.Remove("CarBodyType");
            //removes the above tables from the validation

            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Car/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            ViewData["CarBodyTypeId"] = new SelectList(_context.CarBodyTypes, "CarBodyTypeId", "Description", car.CarBodyTypeId);
            ViewData["CarMakeId"] = new SelectList(_context.CarMakes, "CarMakeId", "Description", car.CarMakeId);
            return View(car);
        }

        // POST: Car/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,CarNo,CarMakeId,CarBodyTypeId,Model,KilometersTravelled,ServiceKilometers,Available")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarBodyTypeId"] = new SelectList(_context.CarBodyTypes, "CarBodyTypeId", "Description", car.CarBodyTypeId);
            ViewData["CarMakeId"] = new SelectList(_context.CarMakes, "CarMakeId", "Description", car.CarMakeId);
            return View(car);
        }

        // GET: Car/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .Include(c => c.CarBodyType)
                .Include(c => c.CarMake)
                .FirstOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Car == null)
            {
                return Problem("Entity set 'RideYouRentContext.Cars'  is null.");
            }
            var car = await _context.Car.FindAsync(id);
            if (car != null)
            {
                _context.Car.Remove(car);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
          return (_context.Car?.Any(e => e.CarId == id)).GetValueOrDefault();
        }
    }
}
// the above code was genertated by Visual Studio Nuget Packet Manager and was adapted to my liking.

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CLDV6221_PoE_Part3.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.IdentityModel.Tokens;

namespace CLDV6221_PoE_Part3.Controllers
{
    public class LoginController : Controller
    {
        private readonly RideYouRentContext _context;

        public LoginController(RideYouRentContext context)
        {
            _context = context;
        }

        // GET: Login
        public async Task<IActionResult> Index(string Username, string Password)
        {
            
            if (_context.Logins == null)
            {
                return Problem("Entity set 'CLDV6221_PoE_Part3Context.Login'  is null.");
            }

            var login =  from l in _context.Logins.Include(l => l.Inspector)
            select l;

            //default to not logged in 
            Loggedin.bLoggedIn = false; //do not show the menue item 
            ViewBag.bLoggedIn = Loggedin.CheckLoggedIn();

            if ((!String.IsNullOrEmpty(Username)) && (!String.IsNullOrEmpty(Password)))
            {
                
                login = login.Where(s => s.Username.Equals(Username) && s.Password.Equals(Password));

                if (!login.IsNullOrEmpty()) //if is empty then we dont have the user and password in the database ie incorrect 
                {
                    Loggedin.bLoggedIn = true; //do not show the menue item 
                    ViewBag.bLoggedIn = Loggedin.CheckLoggedIn();
                    ViewBag.sError = "Login Successful";
                }
                else
                {
                    Loggedin.bLoggedIn = false; //do not show the menue item 
                    ViewBag.bLoggedIn = Loggedin.CheckLoggedIn();
                    ViewBag.sError = "Login Invalid, Please try again";
                }
            }
            return View();
        }

        // GET: Login/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Logins == null)
            {
                return NotFound();
            }

            var login = await _context.Logins
                .Include(l => l.Inspector)
                .FirstOrDefaultAsync(m => m.LoginId == id);
            if (login == null)
            {
                return NotFound();
            }

            return View(login);
        }

        // GET: Login/Create
        public IActionResult Create()
        {
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "InspectorId");
            return View();
        }

        // POST: Login/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoginId,Username,Password,InspectorId")] Login login)
        {
            if (ModelState.IsValid)
            {
                _context.Add(login);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "InspectorId", login.InspectorId);
            return View(login);
        }

        // GET: Login/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Logins == null)
            {
                return NotFound();
            }

            var login = await _context.Logins.FindAsync(id);
            if (login == null)
            {
                return NotFound();
            }
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "InspectorId", login.InspectorId);
            return View(login);
        }

        // POST: Login/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LoginId,Username,Password,InspectorId")] Login login)
        {
            if (id != login.LoginId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(login);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoginExists(login.LoginId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "InspectorId", login.InspectorId);
            return View(login);
        }

        // GET: Login/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Logins == null)
            {
                return NotFound();
            }

            var login = await _context.Logins
                .Include(l => l.Inspector)
                .FirstOrDefaultAsync(m => m.LoginId == id);
            if (login == null)
            {
                return NotFound();
            }

            return View(login);
        }

        // POST: Login/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Logins == null)
            {
                return Problem("Entity set 'RideYouRentContext.Logins'  is null.");
            }
            var login = await _context.Logins.FindAsync(id);
            if (login != null)
            {
                _context.Logins.Remove(login);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoginExists(int id)
        {
          return (_context.Logins?.Any(e => e.LoginId == id)).GetValueOrDefault();
        }
    }
}
// the above code was genertated by Visual Studio Nuget Packet Manager and was adapted to my liking.

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CLDV6221_PoE_Part3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CLDV6221_PoE_Part3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Ride You Rent</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                        </li>
                        <li class="nav-item" @Html.Raw(ViewBag.bLoggedIn)>
                            @*only allows this tab to be visable if they have loggedin successfully*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index" >Car</a>
                        </li>
                        <li class="nav-item" @Html.Raw(ViewBag.bLoggedIn)>
                            @*only allows this tab to be visable if they have loggedin successfully*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index" >Driver</a>
                        </li>
                        <li class="nav-item" @Html.Raw(ViewBag.bLoggedIn)>
                            @*only allows this tab to be visable if they have loggedin successfully*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inspector" asp-action="Index" >Inspector</a>
                        </li>
                        <li class="nav-item" @Html.Raw(ViewBag.bLoggedIn)>
                            @*only allows this tab to be visable if they have loggedin successfully*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rental" asp-action="Index" >Rental</a>
                        </li>
                        <li>
                        <li class="nav-item" @Html.Raw(ViewBag.bLoggedIn)>
                            @*only allows this tab to be visable if they have loggedin successfully*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Return" asp-action="Index">Return</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index" >Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CLDV6221_PoE_Part3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>