Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CLDV6221_PoE_Part3.Models;

namespace CLDV6221_PoE_Part3.Controllers
{
    public class ReturnController : Controller
    {
        private readonly RideYouRentContext _context;

        public ReturnController(RideYouRentContext context)
        {
            ViewBag.bLoggedIn = Loggedin.CheckLoggedIn();
            if (Loggedin.bLoggedIn)
            {
                _context = context;
            }
            else
            {
                _context = context;
                _context.TblReturn = null; //set to null to avoid user bypassing the login and going to the page directly

            }
        }

          public async Task<IActionResult> Index(string searchString)
        {
          

            if (_context.TblReturn == null)
            {
                return Problem("Entity set 'CLDV6221_PoE_Part3Context.Return'  is null.");
            }

            var cars = from c in _context.TblReturn.Include(t => t.Car).Include(t => t.Driver).Include(t => t.Inspector)
            select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                cars = cars.Where(s => s.Car.CarNo.Equals(searchString));
            }

            return View(await cars.ToListAsync());
        }

        // GET: Return/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblReturn == null)
            {
                return NotFound();
            }

            var tblReturn = await _context.TblReturn
                .Include(t => t.Car)
                .Include(t => t.Driver)
                .Include(t => t.Inspector)
                .FirstOrDefaultAsync(m => m.ReturnId == id);
            if (tblReturn == null)
            {
                return NotFound();
            }

            return View(tblReturn);
        }

        // GET: Return/Create
        public IActionResult Create()
        {
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "CarNo");
            ViewData["DriverId"] = new SelectList(_context.Driver, "DriverId", "Name");
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "Name");

            //if (!String.IsNullOrEmpty(dtReturn.ToString))
            //{
                
            //}
            return View();
        }

        // POST: Return/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReturnId,CarId,InspectorId,DriverId,ReturnDate,ElapsedDate,Fine")] TblReturn tblReturn)
        {
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "CarNo", tblReturn.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "DriverId", "Name", tblReturn.DriverId);
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "Name", tblReturn.InspectorId);

            //function to calculate the fine also the elapsed date from now.
            DateTime dtReturn = new DateTime();
            dtReturn = tblReturn.ReturnDate;

            DateTime dtToday = new DateTime();
            dtToday = DateTime.Now;
            //Convert.ToInt32(Math.Floor(dblVal))
            int NoOfDays =Convert.ToInt32(Math.Floor(((dtToday - dtReturn).TotalDays)));
            double dFine = 0;

            if (NoOfDays > 0)
            {
                dFine = NoOfDays * 500;
            }
            else
            {
                dFine = 0;
            }

            ViewBag.ElapsedDate = NoOfDays;
            ViewBag.Fine = dFine;
            //determines the cost of the fee depending on the number of elapsed days.


            ModelState.Remove("Car");
            ModelState.Remove("Driver");
            ModelState.Remove("Inspector");
            //removes the above tables from the vaildation


            if (ModelState.IsValid)
            {
                _context.Add(tblReturn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(tblReturn);
        }

        // GET: Return/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblReturn == null)
            {
                return NotFound();
            }

            var tblReturn = await _context.TblReturn.FindAsync(id);
            if (tblReturn == null)
            {
                return NotFound();
            }
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "CarNo", tblReturn.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "DriverId", "Name", tblReturn.DriverId);
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "Name", tblReturn.InspectorId);
            return View(tblReturn);
        }

        // POST: Return/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReturnId,CarId,InspectorId,DriverId,ReturnDate,ElapsedDate,Fine")] TblReturn tblReturn)
        {
            if (id != tblReturn.ReturnId)
            {
                return NotFound();
            }

            ModelState.Remove("Car");
            ModelState.Remove("Driver");
            ModelState.Remove("Inspector");
            //removes the above tables from the vaildation

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblReturn);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblReturnExists(tblReturn.ReturnId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "CarNo", tblReturn.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "Name", "DriverId", tblReturn.DriverId);
            ViewData["InspectorId"] = new SelectList(_context.Inspector, "InspectorId", "Name", tblReturn.InspectorId);
            return View(tblReturn);
        }

        // GET: Return/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblReturn == null)
            {
                return NotFound();
            }

            var tblReturn = await _context.TblReturn
                .Include(t => t.Car)
                .Include(t => t.Driver)
                .Include(t => t.Inspector)
                .FirstOrDefaultAsync(m => m.ReturnId == id);
            if (tblReturn == null)
            {
                return NotFound();
            }

            return View(tblReturn);
        }

        // POST: Return/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblReturn == null)
            {
                return Problem("Entity set 'RideYouRentContext.TblReturn'  is null.");
            }
            var tblReturn = await _context.TblReturn.FindAsync(id);
            if (tblReturn != null)
            {
                _context.TblReturn.Remove(tblReturn);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblReturnExists(int id)
        {
          return (_context.TblReturn?.Any(e => e.ReturnId == id)).GetValueOrDefault();
        }
    }
}
// the above code was genertated by Visual Studio Nuget Packet Manager and was adapted to my liking.

Views/Return/Create.cshtml
@model CLDV6221_PoE_Part3.Models.TblReturn

@{
    ViewData["Title"] = "Create";
}

<h1>Create Return</h1>



<h4>TblReturn</h4>
<hr />

<div class="row">
    <div class="col-md-4">

           
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CarId" class="control-label">Choose as Car No</label>
                <select asp-for="CarId" class ="form-control" asp-items="ViewBag.CarId"></select>
            </div>
            <div class="form-group">
                <label asp-for="InspectorId" class="control-label">Choose an Inspector</label>
                <select asp-for="InspectorId" class ="form-control" asp-items="ViewBag.InspectorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label">Choose a Driver</label>
                <select asp-for="DriverId" class ="form-control" asp-items="ViewBag.DriverId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" onchange="this.form.submit()" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ElapsedDate" class="control-label"></label>
                <input asp-for="ElapsedDate" class="form-control" value="@ViewBag.ElapsedDate" readonly />
              
            </div>
            <div class="form-group">
                <label asp-for="Fine" class="control-label"></label>
                <input asp-for="Fine" class="form-control" value="@ViewBag.Fine" readonly />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Return/Delete.cshtml
@model CLDV6221_PoE_Part3.Models.TblReturn

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Return</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblReturn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ElapsedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ElapsedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Driver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Driver.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inspector)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inspector.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReturnId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Return/Details.cshtml
@model CLDV6221_PoE_Part3.Models.TblReturn

@{
    ViewData["Title"] = "Details";
}

<h1>Details Return</h1>

<div>
    <h4>TblReturn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ElapsedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ElapsedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Driver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Driver.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inspector)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inspector.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ReturnId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Return/Edit.cshtml
@model CLDV6221_PoE_Part3.Models.TblReturn

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Return</h1>

<h4>TblReturn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReturnId" />
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <select asp-for="CarId" class="form-control" asp-items="ViewBag.CarId"></select>
                <span asp-validation-for="CarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InspectorId" class="control-label"></label>
                <select asp-for="InspectorId" class="form-control" asp-items="ViewBag.InspectorId"></select>
                <span asp-validation-for="InspectorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label"></label>
                <select asp-for="DriverId" class="form-control" asp-items="ViewBag.DriverId"></select>
                <span asp-validation-for="DriverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ElapsedDate" class="control-label"></label>
                <input asp-for="ElapsedDate" class="form-control" />
                <span asp-validation-for="ElapsedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fine" class="control-label"></label>
                <input asp-for="Fine" class="form-control" />
                <span asp-validation-for="Fine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Return/Index.cshtml
@model IEnumerable<CLDV6221_PoE_Part3.Models.TblReturn>

@{
    ViewData["Title"] = "Index";
}

<h1>Index Return</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div>
<form asp-controller="Return" asp-action="Index">
    <p>
        Return: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
    @*the serch funtionality was taken and adapdted from Microsoft
    https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-7.0
    there are 18 contributors*@
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ElapsedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Car)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Driver)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inspector)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ElapsedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Car.CarNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Driver.Name)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Inspector.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReturnId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReturnId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReturnId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>